// Live 3-party choreography test for the SimpleX dispute system (AD-6):
// exercises the exact flow the desktop's disputes.ts orchestrates, against
// REAL SMP relays (needs internet), with three separate core stores:
//
//   OWNER     market operator: business dispute-intake address (auto-accept)
//   BUYER     connects INCOGNITO to the intake; sends the dispute envelope
//             into the per-dispute group the business address creates
//   MODERATOR publishes a personal address; the owner connects and adds
//             them to the dispute group; they join and read/reply
//
// What this validates beyond the smoke test:
//   - the business-address group actually forms on a live relay
//   - WHICH events fire on the buyer side when it does (disputes.ts
//     extractReadyGroupId hard-codes the accepted event shapes)
//   - incognito: the owner must NOT see the buyer's profile name
//   - owner->moderator contact + addMember + moderator join
//   - whether a late-joining moderator sees the pre-join envelope message
//     (SimpleX history forwarding), or needs it re-posted
//
// Run: node apps/desktop/scripts/simplex-choreo.mjs
// Exits 0 printing CHOREO-OK, or 1 with the failed step.

import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';

import { api, util } from 'simplex-chat';
import { T } from '@simplex-chat/types';

const dir = fs.mkdtempSync(path.join(os.tmpdir(), 'simplex-choreo-'));
console.log('stores:', dir);

const ENVELOPE = 'MARKET-DISPUTE-V1 {"marketplaceAddress":"0xtest","package":"<zk-proof-package>"}';
const FOLLOW_UP = 'follow-up: the vendor never shipped, requesting escrow refund';
const MOD_REPLY = 'moderator here: reviewing the proof and the order state';

/** One party: its own core store, profile, started loop, and an event log. */
async function initParty(name, displayName) {
  const chat = await api.ChatApi.init({ type: 'sqlite', filePrefix: path.join(dir, name) });
  const user = await chat.apiCreateActiveUser({ displayName, fullName: '' });
  await chat.startChat();
  const events = [];
  chat.onAny(ev => {
    events.push(ev);
    console.log(`  [${name}] event: ${ev.type}`);
  });
  console.log(`[${name}] profile "${displayName}" userId=${user.userId}`);
  return { chat, user, events, name };
}

/** Waits until the party's event log contains an event matching `pred`. */
function waitFor(party, what, pred, timeoutMs = 180_000) {
  return new Promise((resolve, reject) => {
    const scan = () => party.events.find(pred);
    const first = scan();
    if (first !== undefined) {
      resolve(first);
      return;
    }
    const started = Date.now();
    const iv = setInterval(() => {
      const found = scan();
      if (found !== undefined) {
        clearInterval(iv);
        resolve(found);
      } else if (Date.now() - started > timeoutMs) {
        clearInterval(iv);
        reject(new Error(`[${party.name}] timed out waiting for: ${what}`));
      }
    }, 500);
  });
}

/** The groupId carried by a group-related event, however this version shapes it. */
function eventGroupId(ev) {
  const info = ev.groupInfo ?? ev.chatInfo?.groupInfo ?? ev.chat?.chatInfo?.groupInfo;
  return typeof info?.groupId === 'number' ? info.groupId : null;
}

/** newChatItems events whose text content contains `needle`. */
function chatItemWithText(ev, needle) {
  if (ev.type !== 'newChatItems' || !Array.isArray(ev.chatItems)) return false;
  return ev.chatItems.some(item =>
    JSON.stringify(item.chatItem?.content ?? item).includes(needle),
  );
}

const owner = await initParty('owner', 'Market operator');
const buyer = await initParty('buyer', 'Buyer');
const mod = await initParty('mod', 'mod-alice');

// --- Owner: the dispute-intake business address (publishDisputeIntake's core half)
const ownerLink = await owner.chat.apiCreateUserAddress(owner.user.userId);
await owner.chat.apiSetAddressSettings(owner.user.userId, {
  autoAccept: true,
  businessAddress: true,
  welcomeMessage: 'Dispute intake: send the package generated by your marketplace app.',
});
const intakeAddress = util.contactAddressStr(ownerLink);
console.log('[owner] dispute intake address ready');

// --- Moderator: personal contact address (publishPersonalContact's core half)
const modLink = await mod.chat.apiCreateUserAddress(mod.user.userId);
await mod.chat.apiSetAddressSettings(mod.user.userId, {
  autoAccept: true,
  businessAddress: false,
});
const modAddress = util.contactAddressStr(modLink);
console.log('[mod] personal address ready');

// --- Buyer: connect INCOGNITO to the intake (openDispute's connect step)
//
// FINDING (live, 2026-07-17): apiConnect's `incognito` argument is SILENTLY
// DROPPED by @simplex-chat/types APIConnect.cmdString ("/_connect <userId>
// <link>" -- no incognito field), so the buyer joined as "Buyer_1": their real
// profile name. The core's own syntax takes the flag inline; send the raw
// command instead.
const [, prepared] = await buyer.chat.apiConnectPlan(buyer.user.userId, intakeAddress);
const rawConnect = await buyer.chat.sendChatCmd(
  `/_connect ${buyer.user.userId} incognito=on ${T.CreatedConnLink.cmdString(prepared)}`,
);
console.log(`[buyer] raw incognito connect response: ${rawConnect.type}`);
if (rawConnect.type !== 'sentConfirmation' && rawConnect.type !== 'sentInvitation') {
  throw new Error(`[buyer] raw incognito connect failed: ${JSON.stringify(rawConnect).slice(0, 300)}`);
}
console.log('[buyer] incognito connection to the intake initiated');

// The group the business address creates, as seen from EACH side.
//
// FINDING (live, 2026-07-17): the FIRST group-bearing event on the buyer side
// is groupLinkConnecting -- but sending at that point fails with "not current
// member": the buyer has not finished joining. disputes.ts
// extractReadyGroupId accepts groupLinkConnecting, so deliverOnGroupReady
// fires prematurely and its catch swallows the failure => the envelope never
// delivers on the first attempt. The true ready signal is userJoinedGroup.
const buyerConnectingEv = await waitFor(
  buyer,
  'first group-bearing event (records the premature signal)',
  ev => eventGroupId(ev) !== null,
);
console.log(`[buyer] FIRST group-bearing event: "${buyerConnectingEv.type}" (premature)`);
const buyerGroupEv = await waitFor(
  buyer,
  'userJoinedGroup (actual membership)',
  ev => ev.type === 'userJoinedGroup' && eventGroupId(ev) !== null,
);
const buyerGroupId = eventGroupId(buyerGroupEv);
console.log(`[buyer] group JOINED: groupId=${buyerGroupId} via event "${buyerGroupEv.type}"`);

const ownerGroupEv = await waitFor(
  owner,
  'business group on the owner side',
  ev => eventGroupId(ev) !== null,
);
const ownerGroupId = eventGroupId(ownerGroupEv);
console.log(`[owner] group ready: groupId=${ownerGroupId} via event "${ownerGroupEv.type}"`);

// --- Buyer: deliver the envelope into the group (deliverOnGroupReady's send)
await buyer.chat.apiSendTextMessage(['group', buyerGroupId], ENVELOPE);
console.log('[buyer] envelope sent');

await waitFor(owner, 'the envelope to arrive', ev => chatItemWithText(ev, 'MARKET-DISPUTE-V1'));
console.log('[owner] envelope received');

// --- Incognito check: the owner's view of the buyer member must NOT leak the
// buyer's profile name.
const membersBefore = await owner.chat.apiListMembers(ownerGroupId);
const buyerMember = membersBefore.find(m => m.memberRole !== 'owner');
if (buyerMember === undefined) {
  throw new Error('[owner] no non-owner member in the dispute group');
}
// Recorded (not thrown) so the moderator leg still runs; the exit code at the
// end reflects it.
const incognitoHolds = !buyerMember.localDisplayName.toLowerCase().includes('buyer');
console.log(
  incognitoHolds
    ? `[owner] incognito holds: buyer appears as "${buyerMember.localDisplayName}"`
    : `[owner] INCOGNITO LEAK: buyer appears as "${buyerMember.localDisplayName}"`,
);

// --- Owner: connect to the moderator's personal address (inviteModerator's
// first half). Not incognito: the operator is not hiding from their own mod.
const [, modPrepared] = await owner.chat.apiConnectPlan(owner.user.userId, modAddress);
await owner.chat.apiConnect(owner.user.userId, false, modPrepared);
await waitFor(owner, 'moderator contact to connect', ev => ev.type === 'contactConnected');
console.log('[owner] moderator is now a contact');

// inviteModerator's weak spot: it takes the FIRST contact. Check what the
// owner's contact list actually holds at this point (business-chat buyers may
// or may not appear as contacts).
const ownerContacts = await owner.chat.apiListContacts(owner.user.userId);
console.log(
  '[owner] contacts now:',
  ownerContacts.map(c => `${c.contactId}:${c.localDisplayName}`).join(', ') || '(none)',
);
const modContact = ownerContacts.find(c => c.localDisplayName.includes('mod-alice'));
if (modContact === undefined) {
  throw new Error('[owner] moderator not found in contacts by display name');
}

// --- Owner: add the moderator to the dispute group
await owner.chat.apiAddMember(ownerGroupId, modContact.contactId, 'admin');
console.log('[owner] moderator added to the dispute group');

// --- Moderator: join on invitation
const invitation = await waitFor(
  mod,
  'group invitation',
  ev => ev.type === 'receivedGroupInvitation' && eventGroupId(ev) !== null,
);
const modGroupId = eventGroupId(invitation);
await mod.chat.apiJoinGroup(modGroupId);
await waitFor(mod, 'own group join to complete', ev => ev.type === 'userJoinedGroup');
console.log(`[mod] joined the dispute group (groupId=${modGroupId})`);

// --- Does the late joiner see the pre-join envelope? (history forwarding)
await new Promise(r => setTimeout(r, 5_000)); // let history/deliveries settle
const modChat = await mod.chat.apiGetChat('group', modGroupId, 50);
const historyHasEnvelope = JSON.stringify(modChat).includes('MARKET-DISPUTE-V1');
console.log(`[mod] pre-join envelope visible in history: ${historyHasEnvelope}`);

// --- Live 3-way exchange: buyer follow-up reaches the mod; mod reply reaches
// buyer AND owner.
await buyer.chat.apiSendTextMessage(['group', buyerGroupId], FOLLOW_UP);
await waitFor(mod, "the buyer's follow-up", ev => chatItemWithText(ev, 'escrow refund'));
console.log('[mod] received the buyer follow-up');

await mod.chat.apiSendTextMessage(['group', modGroupId], MOD_REPLY);
await waitFor(buyer, "the moderator's reply", ev => chatItemWithText(ev, 'moderator here'));
await waitFor(owner, "the moderator's reply", ev => chatItemWithText(ev, 'moderator here'));
console.log('[buyer+owner] received the moderator reply');

// --- Summary: which event types fired where (validates extractReadyGroupId)
for (const p of [owner, buyer, mod]) {
  const types = [...new Set(p.events.map(e => e.type))];
  console.log(`[${p.name}] distinct event types: ${types.join(', ')}`);
}
console.log(`buyer group-ready event type: ${buyerGroupEv.type}`);
console.log(`history forwarding to late joiner: ${historyHasEnvelope}`);
console.log(`incognito holds: ${incognitoHolds}`);

await owner.chat.stopChat();
await buyer.chat.stopChat();
await mod.chat.stopChat();
if (!incognitoHolds) {
  console.log('CHOREO-FAILED: incognito leaked');
  process.exit(1);
}
console.log('CHOREO-OK');
process.exit(0);
