// Dispute orchestration (AD-6): ties together the buyer commit-reveal
// authentication, the on-chain attested contact addresses (@market/deployment),
// and the embedded SimpleX core (./simplex) into the end-to-end dispute flow.
//
//   Owner  -> publishDisputeIntake: create a SimpleX business address and
//             attest it on-chain under the owner identity. Buyers connecting
//             to it each land in a fresh group with the owner.
//   Buyer  -> openDispute: publish a commitment to a per-order secret on-chain
//             (only the buyer can -- dispute_order spends their order note),
//             connect INCOGNITO (unlinkable), and reveal the secret in the room
//             once the group forms.
//   Owner/ -> verifyDisputeEnvelope: recompute the commitment from the revealed
//   mods     secret and match it against the on-chain value plus the market's
//            accepted/disputed/unsettled state; inviteModerator pulls a mod's
//            attested address into the dispute group.
//
// The buyer's Aztec address is never in the envelope; moderators learn only
// WHICH order is disputed, authenticated genuine, never who placed it.

import { Fr } from '@aztec/aztec.js/fields';
import {
  getContactAddress,
  getDisputeCommitment,
  getOrderDisputeState,
  getSuperadminIdentity,
  markOrderDisputed,
  setContactAddress,
  type OrderView,
  type ResolvedMarketplace,
} from '@market/deployment';
import { deriveDisputeCommitment } from '@market/identity';

import { getOrCreateDisputeSecret } from './orderCredentials.js';
import { marketAction, type Session, type TransactionalSession } from './session.js';
import {
  ensureDisputeAddress,
  ensureMarketProfile,
  ensurePersonalAddress,
  simplex,
  type SimplexGroupMember,
} from './simplex.js';

// ---------------------------------------------------------------------------
// Dispute envelope (AD-6): the small, tagged message a buyer reveals in the
// dispute room. It carries the order id, the complaint, and the buyer's
// dispute SECRET. Revealing the secret -- whose poseidon2 commitment the buyer
// already published on-chain via dispute_order (which only the buyer can call)
// -- is what authenticates them. It replaces the old ~15KB UltraHonk proof:
// a few hundred bytes, delivered in a single message, verified automatically
// by one hash, with no copy-paste.
// ---------------------------------------------------------------------------

export const DISPUTE_ENVELOPE_TAG = 'aztec-market/dispute/v2';

export interface DisputeEnvelope {
  tag: typeof DISPUTE_ENVELOPE_TAG;
  marketplaceAddress: string;
  orderId: string;
  statement: string;
  /** The buyer's dispute secret (hex); revealing it IS the authentication. */
  secret: string;
}

export function serializeDisputeEnvelope(envelope: DisputeEnvelope): string {
  if (envelope.tag !== DISPUTE_ENVELOPE_TAG) {
    throw new Error('refusing to serialize a dispute envelope with the wrong tag');
  }
  return JSON.stringify(envelope);
}

/**
 * Parses a message body as a dispute envelope, or null if it is ordinary chat.
 * Throws only on a body that claims the tag but is malformed.
 */
export function parseDisputeEnvelope(body: string): DisputeEnvelope | null {
  let parsed: unknown;
  try {
    parsed = JSON.parse(body);
  } catch {
    return null;
  }
  if (
    typeof parsed !== 'object' ||
    parsed === null ||
    (parsed as { tag?: unknown }).tag !== DISPUTE_ENVELOPE_TAG
  ) {
    return null;
  }
  const e = parsed as Record<string, unknown>;
  if (
    typeof e.marketplaceAddress !== 'string' ||
    typeof e.orderId !== 'string' ||
    typeof e.statement !== 'string' ||
    typeof e.secret !== 'string'
  ) {
    throw new Error('malformed dispute envelope');
  }
  return {
    tag: DISPUTE_ENVELOPE_TAG,
    marketplaceAddress: e.marketplaceAddress,
    orderId: e.orderId,
    statement: e.statement,
    secret: e.secret,
  };
}

/**
 * A friendly summary of a dispute-envelope message, for rendering it in a
 * thread as a readable card instead of raw JSON. Null for ordinary messages.
 */
export function summarizeDisputeEnvelope(
  body: string,
): { orderId: string; statement: string } | null {
  let envelope: DisputeEnvelope | null;
  try {
    envelope = parseDisputeEnvelope(body);
  } catch {
    return null;
  }
  return envelope === null ? null : { orderId: envelope.orderId, statement: envelope.statement };
}

// ---------------------------------------------------------------------------
// Owner: publish the dispute-intake address
// ---------------------------------------------------------------------------

const DISPUTE_WELCOME =
  'This is the dispute channel for a hidden market. Send the dispute package generated by ' +
  'your marketplace app; a moderator will review it.';

/**
 * Owner action: create (or reuse) the market's SimpleX business address and
 * attest it on-chain under the owner identity, so buyers can find it. Returns
 * the address link.
 */
export async function publishDisputeIntake(
  session: TransactionalSession,
  market: ResolvedMarketplace,
  accessSecret: Fr,
): Promise<string> {
  const marketAddr = market.marketplaceAddress.toString();
  const link = await ensureDisputeAddress(marketAddr, 'Market operator', DISPUTE_WELCOME);
  await setContactAddress({
    wallet: session.wallet,
    node: session.node,
    from: session.from,
    ...marketAction(session),
    marketplaceAddress: market.marketplaceAddress,
    accessSecret,
    simplexAddress: link,
  });
  return link;
}

/** Resolves the market's dispute-intake address (published by the owner). */
export async function resolveDisputeIntake(
  viewer: Session,
  market: ResolvedMarketplace,
  accessSecret: Fr,
): Promise<string | null> {
  const common = {
    wallet: viewer.wallet,
    node: viewer.node,
    from: viewer.from,
    marketplaceAddress: market.marketplaceAddress,
  };
  const superadminIdentity = await getSuperadminIdentity(common);
  return getContactAddress({ ...common, identity: superadminIdentity, accessSecret });
}

// ---------------------------------------------------------------------------
// Moderator/vendor: publish a personal contact address (so they can be added)
// ---------------------------------------------------------------------------

/**
 * Publishes the caller's personal SimpleX address on-chain under their derived
 * identity, so the owner's dispute automation can add them to a group. Used by
 * moderators (and vendors, if looped in).
 */
export async function publishPersonalContact(
  session: TransactionalSession,
  market: ResolvedMarketplace,
  accessSecret: Fr,
  displayName: string,
): Promise<string> {
  const link = await ensurePersonalAddress(market.marketplaceAddress.toString(), displayName);
  await setContactAddress({
    wallet: session.wallet,
    node: session.node,
    from: session.from,
    ...marketAction(session),
    marketplaceAddress: market.marketplaceAddress,
    accessSecret,
    simplexAddress: link,
  });
  return link;
}

// ---------------------------------------------------------------------------
// Buyer: open a dispute
// ---------------------------------------------------------------------------

export interface OpenDisputeResult {
  /** The auth envelope revealed into the dispute room. */
  envelope: DisputeEnvelope;
  /** The serialized envelope text, so the buyer can resend it manually. */
  wire: string;
}

/**
 * Buyer action: bind the dispute on-chain (publishing the buyer's auth
 * commitment and flipping the anonymous DISPUTED flag), connect incognito to
 * the market's dispute address, and reveal the auth envelope into the group the
 * operator opens. Returns the envelope immediately; delivery completes when the
 * operator's client is next online to accept the connection.
 *
 * Authentication no longer needs the order nonce or a ZK proof: the buyer's
 * ability to call dispute_order (it spends their order note) is what proves
 * buyer-ship, and the revealed secret ties the anonymous room back to that.
 */
export async function openDispute(
  session: TransactionalSession,
  market: ResolvedMarketplace,
  accessSecret: Fr,
  order: OrderView,
  statement: string,
): Promise<OpenDisputeResult> {
  if (statement.trim().length === 0) {
    throw new Error('a dispute needs a statement describing the problem');
  }
  const intake = await resolveDisputeIntake(session, market, accessSecret);
  if (intake === null) {
    throw new Error(
      'this market has not published a dispute channel yet; contact the operator another way',
    );
  }

  // The buyer's per-order authentication secret (stable across retries) and its
  // on-chain commitment.
  const secret = getOrCreateDisputeSecret(order.orderId.toString());
  const commitment = await deriveDisputeCommitment(Fr.fromString(secret));

  // Bind the dispute ON-CHAIN first: dispute_order publishes `commitment` and
  // flips the anonymous flag, which blocks the vendor's timeout settlement, so
  // the order can only end by the buyer confirming or the vendor refunding
  // while the dispute is argued in the room. Skipped if already set (a retry
  // after a messaging failure), in which case the commitment is already live
  // and `secret` -- read back from local storage -- still matches it.
  const state = await getOrderDisputeState({
    wallet: session.wallet,
    node: session.node,
    // The buyer is the universal account, which owns and disputes the order.
    from: session.universal,
    marketplaceAddress: market.marketplaceAddress,
    orderId: order.orderId,
  });
  if (!state.disputed) {
    await markOrderDisputed({
      wallet: session.wallet,
      node: session.node,
      from: session.universal,
      fee: { paymentMethod: session.universalPaymentMethod },
      marketplaceAddress: market.marketplaceAddress,
      orderId: order.orderId,
      disputeCommitment: commitment,
    });
  }

  const envelope: DisputeEnvelope = {
    tag: DISPUTE_ENVELOPE_TAG,
    marketplaceAddress: market.marketplaceAddress.toString(),
    orderId: order.orderId.toString(),
    statement: statement.trim(),
    secret,
  };
  const wire = serializeDisputeEnvelope(envelope);

  // Buyers dispute under a per-market profile, but connect INCOGNITO so the
  // dispute links to neither their market pseudonym nor other disputes.
  const buyerProfile = await ensureMarketProfile(
    market.marketplaceAddress.toString(),
    'Buyer',
  );
  await simplex().connect(buyerProfile.userId, intake, true);
  // Reveal the auth envelope into the group the operator opens. Unlike the old
  // ~15KB proof (which exceeded the core's single-message cap and needed a
  // manual paste), this is a few hundred bytes, so it delivers in one message
  // and the moderator's client verifies it automatically.
  await deliverOnGroupReady(buyerProfile.userId, wire);

  return { envelope, wire };
}

/**
 * One-shot: when the next group becomes ready for `userId` (the operator
 * accepted the incognito connection), send `wire` into it. Returns after the
 * handler is armed; the send happens asynchronously.
 */
function deliverOnGroupReady(userId: number, wire: string): Promise<void> {
  return new Promise(resolve => {
    const bridge = simplex();
    const unsubscribe = bridge.onEvent(event => {
      // A business-address connection surfaces as a group the buyer joins.
      const groupId = extractReadyGroupId(event);
      if (groupId === null) {
        return;
      }
      unsubscribe();
      void bridge.sendText(userId, 'group', groupId, wire).catch(err => {
        // The buyer keeps `wire` and can resend it manually from the dispute
        // view; still, a failed first delivery must not vanish silently.
        console.error('dispute envelope delivery failed; resend it manually:', err);
      });
    });
    resolve();
  });
}

function extractReadyGroupId(event: { type: string } & Record<string, unknown>): number | null {
  // LIVE-VERIFIED (simplex-choreo, 2026-07-17): the business-address connect
  // emits groupLinkConnecting (and chat items) BEFORE membership completes --
  // sending then fails with "not current member". userJoinedGroup is the one
  // signal that the buyer is actually in the group.
  if (event.type !== 'userJoinedGroup') {
    return null;
  }
  const info = (event.groupInfo ?? (event as { chatInfo?: { groupInfo?: unknown } }).chatInfo) as
    | { groupId?: unknown }
    | undefined;
  const groupId = info?.groupId;
  return typeof groupId === 'number' ? groupId : null;
}

// ---------------------------------------------------------------------------
// Moderator: verify a received dispute envelope
// ---------------------------------------------------------------------------

export interface DisputeVerdict {
  ok: boolean;
  /** The revealed secret opens the on-chain commitment (the genuine buyer). */
  secretValid: boolean;
  /** The envelope is about THIS market. */
  marketMatches: boolean;
  /** The order was accepted by its vendor (the vendor committed). */
  accepted: boolean;
  /** The order is still unsettled (the dispute is live). */
  live: boolean;
  /** The buyer marked the order disputed on-chain (binding: it blocks the
   * vendor's timeout settlement). */
  disputed: boolean;
  /** A human-readable summary for the UI badge. */
  summary: string;
}

/**
 * Verifies a dispute envelope for a moderator, automatically and offline: the
 * revealed secret must open the commitment the buyer published on-chain (a
 * single poseidon2), and the order must be accepted, disputed, and unsettled.
 * Only the buyer could have set that commitment (dispute_order spends their
 * order note), so a match authenticates the anonymous room participant as the
 * buyer -- no ZK proof, and no buyer address is ever revealed. Every check is a
 * free utility read.
 */
export async function verifyDisputeEnvelope(
  viewer: Session,
  market: ResolvedMarketplace,
  envelope: DisputeEnvelope,
): Promise<DisputeVerdict> {
  const marketMatches = envelope.marketplaceAddress === market.marketplaceAddress.toString();
  const common = {
    wallet: viewer.wallet,
    node: viewer.node,
    from: viewer.from,
    marketplaceAddress: market.marketplaceAddress,
  };

  let secretValid = false;
  let accepted = false;
  let live = false;
  let disputed = false;
  if (marketMatches) {
    const orderId = Fr.fromString(envelope.orderId);
    const expected = await deriveDisputeCommitment(Fr.fromString(envelope.secret));
    const onChain = await getDisputeCommitment({ ...common, orderId });
    // A never-disputed order stores a zero commitment; require a real match.
    secretValid = !onChain.isZero() && onChain.equals(expected);
    const state = await getOrderDisputeState({ ...common, orderId });
    accepted = state.accepted;
    live = !state.settled;
    disputed = state.disputed;
  }

  const ok = marketMatches && secretValid && accepted && live && disputed;
  const summary = !marketMatches
    ? 'this dispute is for a different market'
    : !disputed
      ? 'order is not marked disputed on-chain — ask the buyer to open the dispute in their app'
      : !secretValid
        ? 'verification code does not match — not the genuine buyer'
        : !accepted
          ? 'order was never accepted by the vendor'
          : !live
            ? 'order already settled — dispute is moot'
            : 'verified: the genuine buyer of an accepted, disputed order';
  return { ok, secretValid, marketMatches, accepted, live, disputed, summary };
}

// ---------------------------------------------------------------------------
// Owner: invite a moderator into a dispute group
// ---------------------------------------------------------------------------

/**
 * The device-local moderator-identity -> SimpleX contactId binding, learned
 * from the contactConnected event when the operator's connection to that
 * moderator's address completes. SimpleX never exposes which address a
 * contact came from, so this capture is the only reliable link.
 */
const MOD_CONTACT_KEY_PREFIX = 'market.simplexModContact.v1.';

/**
 * How long to wait for the moderator's client to auto-accept the connection
 * before giving up and telling the operator to try again. Acceptance is
 * near-instant when their app is open on this market; this only bounds the
 * case where it is not.
 */
const CONTACT_ACCEPT_TIMEOUT_MS = 20_000;

/**
 * Adds a moderator (by their marketplace identity) to a dispute group: resolves
 * their attested SimpleX address, connects if not already a contact, and adds
 * them to the group. `ownerUserId` is the operator's per-market SimpleX
 * profile that owns the group.
 *
 * Contact establishment over SimpleX is asynchronous: on first use this sends
 * the connection request, records the resulting contactId when the moderator
 * accepts, and asks the caller to retry; from then on the stored binding is
 * used. LIVE-VERIFIED: business-chat buyers never appear in the operator's
 * contact list, so a single contact on file is unambiguous.
 */
export async function inviteModerator(
  viewer: Session,
  market: ResolvedMarketplace,
  accessSecret: Fr,
  params: { ownerUserId: number; groupId: number; moderatorIdentity: Fr },
): Promise<{ added: boolean; reason?: string }> {
  const address = await getContactAddress({
    wallet: viewer.wallet,
    node: viewer.node,
    from: viewer.from,
    marketplaceAddress: market.marketplaceAddress,
    identity: params.moderatorIdentity,
    accessSecret,
  });
  if (address === null) {
    return { added: false, reason: 'this moderator has not published a contact address' };
  }

  const bridge = simplex();
  const key = `${MOD_CONTACT_KEY_PREFIX}${market.marketplaceAddress.toString()}:${params.moderatorIdentity.toString()}`;
  const contacts = await bridge.listContacts(params.ownerUserId);

  const storedId = localStorage.getItem(key);
  let contact = storedId !== null ? contacts.find(c => c.contactId === Number(storedId)) : undefined;
  // With exactly one contact on file there is nothing to confuse it with, so
  // adopt it. Beyond that we do NOT guess: SimpleX never reveals which address
  // a contact arrived from, and binding the wrong one would add a stranger to a
  // dispute room.
  if (contact === undefined && contacts.length === 1) {
    contact = contacts[0];
  }

  if (contact !== undefined) {
    localStorage.setItem(key, String(contact.contactId));
    try {
      await bridge.addMember(params.ownerUserId, params.groupId, contact.contactId, 'admin');
    } catch (err) {
      // Already a member is a success, not a failure: re-inviting is the
      // natural thing to do when the operator cannot see whether it worked.
      const text = err instanceof Error ? err.message : String(err);
      if (/already|duplicate|exists/i.test(text)) {
        return { added: true };
      }
      return { added: false, reason: `could not add them to the room: ${text}` };
    }
    return { added: true };
  }

  // Not a contact yet, or several contacts and no recorded binding. Connect to
  // the attested address, WAIT for the moderator's client to accept, then add
  // them -- so one click does the whole thing when they are online.
  //
  // The capture is a BEFORE/AFTER DIFF, not "the next contactConnected event":
  // the operator may have other connections completing at the same time, and
  // binding one of those would put the wrong person in a dispute room.
  const before = new Set(contacts.map(c => c.contactId));
  let settle: (id: number | null) => void = () => {};
  const accepted = new Promise<number | null>(resolve => {
    settle = resolve;
  });
  const unsubscribe = bridge.onEvent(event => {
    if (event.type !== 'contactConnected') {
      return;
    }
    const connected = (event as { contact?: { contactId?: unknown } }).contact;
    if (typeof connected?.contactId !== 'number' || before.has(connected.contactId)) {
      return; // someone else's connection completing; keep listening
    }
    settle(connected.contactId);
  });
  const timer = setTimeout(() => settle(null), CONTACT_ACCEPT_TIMEOUT_MS);
  const done = () => {
    clearTimeout(timer);
    unsubscribe();
  };

  try {
    await bridge.connect(params.ownerUserId, address, false);
  } catch (err) {
    done();
    const text = err instanceof Error ? err.message : String(err);
    // Already connected, but we have no binding and cannot pick them out of
    // several contacts. Say so plainly -- reporting "invitation sent" here
    // would loop forever, since no new contact will ever connect.
    if (/already|duplicate|exists/i.test(text)) {
      return {
        added: false,
        reason:
          `already connected to this moderator, but this device cannot tell which of the ` +
          `${contacts.length} contacts they are (SimpleX does not reveal which address a ` +
          `contact came from). Remove the stale contact in Messages and invite again.`,
      };
    }
    return { added: false, reason: `could not connect to this moderator's address: ${text}` };
  }

  const contactId = await accepted;
  done();
  if (contactId === null) {
    return {
      added: false,
      reason:
        'invitation sent, but their app has not accepted it yet. It accepts automatically ' +
        'whenever they have this market open; invite again once they do.',
    };
  }
  localStorage.setItem(key, String(contactId));
  await bridge.addMember(params.ownerUserId, params.groupId, contactId, 'admin');
  return { added: true };
}

/**
 * Moderator-side counterpart: accept dispute-group invitations. Sweeps groups
 * this profile was already invited to (invitations that arrived while the app
 * was closed) and auto-joins new ones live until unsubscribed.
 *
 * LIVE-VERIFIED: the operator's addMember alone does NOT place the moderator
 * in the group -- without this join step the invitation sits unanswered
 * forever and the moderator never sees the dispute.
 */
export async function moderatorAutoJoin(
  marketAddress: string,
  displayName: string,
): Promise<{ swept: number; unsubscribe: () => void }> {
  const profile = await ensureMarketProfile(marketAddress, displayName);
  const bridge = simplex();

  const groups = await bridge.listGroups(profile.userId);
  let swept = 0;
  for (const group of groups) {
    if (group.membership?.memberStatus === 'invited') {
      await bridge.joinGroup(profile.userId, group.groupId);
      swept += 1;
    }
  }

  const unsubscribe = bridge.onEvent(event => {
    if (event.type !== 'receivedGroupInvitation') {
      return;
    }
    const info = (event as { groupInfo?: { groupId?: unknown } }).groupInfo;
    if (typeof info?.groupId === 'number') {
      void bridge.joinGroup(profile.userId, info.groupId).catch(err => {
        console.error(`failed to join dispute group ${info.groupId}:`, err);
      });
    }
  });
  return { swept, unsubscribe };
}

/** Whether an order is eligible for a buyer to open a dispute over. */
export function orderIsDisputable(order: OrderView): boolean {
  return order.accepted && !order.settled;
}

export type { SimplexGroupMember };
