#!/usr/bin/env bash
# Generates TypeScript bindings from compiled contract artifacts into
# packages/contract-bindings. Requires scripts/compile.sh to have run first.
set -euo pipefail
. "$HOME/aztec-env.sh"
ROOT="$(cd "$(dirname "$0")/.." && pwd)"

OUT="$ROOT/packages/contract-bindings/src/artifacts"
mkdir -p "$OUT"

for pkg in marketplace-registry marketplace order-escrow; do
  echo "=== aztec codegen: contracts/$pkg ==="
  (cd "$ROOT/contracts/$pkg" && aztec codegen target --outdir "$OUT")
  # Localize the artifact JSON so the bindings package is self-contained:
  # copy it next to the generated .ts and rewrite the deep relative import.
  cp "$ROOT/contracts/$pkg"/target/*.json "$OUT/"
done
sed -i -E "s#'(\.\./)+contracts/[a-z-]+/target/([^']+\.json)'#'./\2'#" "$OUT"/*.ts

# Emit the package index re-exporting every generated binding.
INDEX="$ROOT/packages/contract-bindings/src/index.ts"
{
  echo "// Autogenerated by scripts/codegen.sh -- do not edit."
  for f in "$OUT"/*.ts; do
    base="$(basename "$f" .ts)"
    echo "export * from './artifacts/${base}.js';"
  done
} > "$INDEX"

echo "codegen: bindings written to packages/contract-bindings/src/artifacts"
